# Generated by Django 5.1.1 on 2024-10-04 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_order_options_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
    ]
