# Generated by Django 5.1.1 on 2024-10-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_descriptionimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiration_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
