# Generated by Django 5.1.1 on 2024-10-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='shipping_fee',
            field=models.CharField(default=100.0, max_length=100),
        ),
    ]
