# Generated by Django 5.1.1 on 2024-10-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_alter_shipping_shipping_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='shipping_fee',
            field=models.IntegerField(default=100.0),
        ),
    ]
