# Generated by Django 5.1.2 on 2024-10-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('price', models.IntegerField()),
                ('mainimage', models.ImageField(blank=True, upload_to='photos/store')),
                ('subimage1', models.ImageField(blank=True, upload_to='photos/store')),
                ('subimage2', models.ImageField(blank=True, upload_to='photos/store')),
                ('subimage3', models.ImageField(blank=True, upload_to='photos/store')),
                ('desimage1', models.ImageField(blank=True, upload_to='photos/store')),
                ('desimage2', models.ImageField(blank=True, upload_to='photos/store')),
                ('desimage3', models.ImageField(blank=True, upload_to='photos/store')),
                ('desimage4', models.ImageField(blank=True, upload_to='photos/store')),
            ],
        ),
    ]
