# Generated by Django 5.1.2 on 2024-10-24 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='desimage4',
        ),
    ]
