# Generated by Django 5.1.2 on 2024-10-26 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
