# Generated by Django 5.1.2 on 2024-10-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='desimage4',
            field=models.ImageField(blank=True, upload_to='photos/store'),
        ),
        migrations.AddField(
            model_name='items',
            name='desimage5',
            field=models.ImageField(blank=True, upload_to='photos/store'),
        ),
        migrations.AddField(
            model_name='items',
            name='desimage6',
            field=models.ImageField(blank=True, upload_to='photos/store'),
        ),
        migrations.AddField(
            model_name='items',
            name='desimage7',
            field=models.ImageField(blank=True, upload_to='photos/store'),
        ),
        migrations.AddField(
            model_name='items',
            name='desimage8',
            field=models.ImageField(blank=True, upload_to='photos/store'),
        ),
        migrations.AddField(
            model_name='items',
            name='subimage4',
            field=models.ImageField(blank=True, upload_to='photos/store'),
        ),
        migrations.AddField(
            model_name='items',
            name='subimage5',
            field=models.ImageField(blank=True, upload_to='photos/store'),
        ),
        migrations.AddField(
            model_name='items',
            name='subimage6',
            field=models.ImageField(blank=True, upload_to='photos/store'),
        ),
        migrations.AddField(
            model_name='items',
            name='subimage7',
            field=models.ImageField(blank=True, upload_to='photos/store'),
        ),
        migrations.AddField(
            model_name='items',
            name='subimage8',
            field=models.ImageField(blank=True, upload_to='photos/store'),
        ),
    ]
